export const INIT_AUTH = 'INIT_AUTH'
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'

export const FETCHING_LOCATION = 'FETCHING_LOCATION'
export const LOCATION_FETCHED = 'LOCATION_FETCHED'
export const LOCATION_NOT_FETCHED = 'LOCATION_NOT_FETCHED'
